build: fix caddy installation for CI workflow (#33)
CI was failing with:

  W: GPG error:
  https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease:
  The following signatures couldn't be verified because the public key is not available:
  NO_PUBKEY ABA1F9B8875A6661
  E: The repository
  'https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease'
  is not signed.
  Error: Process completed with exit code 100.

We update the caddyfile installation in the
test.yml workflow based on these instructions:
https://caddyserver.com/docs/install#debian-ubuntu-raspbian